export const data = {
  images: [
    {
      _id: 1,
      imageSrc: '/images/pexels-akos-adorjan-3788425(1).jpg',
      price: 5,
    },
    {
      _id: 2,
      imageSrc: '/images/pexels-akos-adorjan-3788425.jpg',
      price: 5,
    },
    {
      _id: 3,
      imageSrc: '/images/pexels-anderson-guerra-1115128.jpg',
      price: 5,
    },
    {
      _id: 4,
      imageSrc: '/images/pexels-andrea-piacquadio-3807758.jpg',
      price: 5,
    },
    {
      _id: 5,
      imageSrc: '/images/pexels-anete-lusina-4790579.jpg',
      price: 5,
    },
    {
      _id: 6,
      imageSrc: '/images/pexels-anete-lusina-5721905(1).jpg',
      price: 5,
    },
    {
      _id: 7,
      imageSrc: '/images/pexels-anete-lusina-5721905.jpg',
      price: 5,
    },
    {
      _id: 8,
      imageSrc: '/images/pexels-anete-lusina-5721906.jpg',
      price: 5,
    },
    {
      _id: 9,
      imageSrc: '/images/pexels-angela-roma-7319097.jpg',
      price: 5,
    },
    {
      _id: 10,
      imageSrc: '/images/pexels-angela-roma-7319318.jpg',
      price: 5,
    },
    { _id: 11, imageSrc: '/images/pexels-ann-poan-5797991.jpg', price: 5 },
    {
      _id: 12,
      imageSrc: '/images/pexels-anna-shvets-5217899.jpg',
      price: 5,
    },
    { _id: 13, imageSrc: '/images/pexels-cottonbro-8297195.jpg', price: 5 },
    { _id: 14, imageSrc: '/images/pexels-cottonbro-8297202.jpg', price: 5 },
    {
      _id: 15,
      imageSrc: '/images/pexels-david-waschbüsch-1887946.jpg',
      price: 5,
    },
    {
      _id: 16,
      imageSrc: '/images/pexels-enric-cruz-lópez-7444978(1).jpg',
      price: 5,
    },
    {
      _id: 17,
      imageSrc: '/images/pexels-enric-cruz-lópez-7444978.jpg',
      price: 5,
    },
    {
      _id: 18,
      imageSrc: '/images/pexels-ioana-motoc-4346281(1).jpg',
      price: 5,
    },
    {
      _id: 19,
      imageSrc: '/images/pexels-ioana-motoc-4346281.jpg',
      price: 5,
    },
    {
      _id: 20,
      imageSrc: '/images/pexels-ioana-motoc-4346282.jpg',
      price: 5,
    },
    {
      _id: 21,
      imageSrc: '/images/pexels-ioana-motoc-4346305(1).jpg',
      price: 5,
    },
    {
      _id: 22,
      imageSrc: '/images/pexels-ioana-motoc-4346305.jpg',
      price: 5,
    },
    {
      _id: 23,
      imageSrc: '/images/pexels-jill-burrow-5987212.jpg',
      price: 5,
    },
    {
      _id: 24,
      imageSrc: '/images/pexels-jill-burrow-6069745.jpg',
      price: 5,
    },
    { _id: 25, imageSrc: '/images/pexels-jose-musa-8980193.jpg', price: 5 },
    {
      _id: 26,
      imageSrc: '/images/pexels-karolina-grabowska-4016512.jpg',
      price: 5,
    },
    {
      _id: 27,
      imageSrc: '/images/pexels-karolina-grabowska-4022220(1).jpg',
      price: 5,
    },
    {
      _id: 28,
      imageSrc: '/images/pexels-karolina-grabowska-4022220.jpg',
      price: 5,
    },
    {
      _id: 29,
      imageSrc: '/images/pexels-karolina-grabowska-4040599.jpg',
      price: 5,
    },
    {
      _id: 30,
      imageSrc: '/images/pexels-karolina-grabowska-4041279.jpg',
      price: 5,
    },
    {
      _id: 31,
      imageSrc: '/images/pexels-karolina-grabowska-4041283(1).jpg',
      price: 5,
    },
    {
      _id: 32,
      imageSrc: '/images/pexels-karolina-grabowska-4041283.jpg',
      price: 5,
    },
    {
      _id: 33,
      imageSrc: '/images/pexels-karolina-grabowska-4041285.jpg',
      price: 5,
    },
    {
      _id: 34,
      imageSrc: '/images/pexels-karolina-grabowska-4202322.jpg',
      price: 5,
    },
    {
      _id: 35,
      imageSrc: '/images/pexels-karolina-grabowska-4202325.jpg',
      price: 5,
    },
    {
      _id: 36,
      imageSrc: '/images/pexels-karolina-grabowska-4202326(1).jpg',
      price: 5,
    },
    {
      _id: 37,
      imageSrc: '/images/pexels-karolina-grabowska-4202326.jpg',
      price: 5,
    },
    {
      _id: 38,
      imageSrc: '/images/pexels-karolina-grabowska-4202328.jpg',
      price: 5,
    },
    {
      _id: 39,
      imageSrc: '/images/pexels-karolina-grabowska-4202918.jpg',
      price: 5,
    },
    {
      _id: 40,
      imageSrc: '/images/pexels-karolina-grabowska-4203070.jpg',
      price: 5,
    },
    {
      _id: 41,
      imageSrc: '/images/pexels-karolina-grabowska-4207620(1).jpg',
      price: 5,
    },
    {
      _id: 42,
      imageSrc: '/images/pexels-karolina-grabowska-4207620.jpg',
      price: 5,
    },
    {
      _id: 43,
      imageSrc: '/images/pexels-karolina-grabowska-4210315(1).jpg',
      price: 5,
    },
    {
      _id: 44,
      imageSrc: '/images/pexels-karolina-grabowska-4210315.jpg',
      price: 5,
    },
    {
      _id: 45,
      imageSrc: '/images/pexels-karolina-grabowska-4210317.jpg',
      price: 5,
    },
    {
      _id: 46,
      imageSrc: '/images/pexels-karolina-grabowska-4210340(1).jpg',
      price: 5,
    },
    {
      _id: 47,
      imageSrc: '/images/pexels-karolina-grabowska-4210340.jpg',
      price: 5,
    },
    {
      _id: 48,
      imageSrc: '/images/pexels-karolina-grabowska-4210370.jpg',
      price: 5,
    },
    {
      _id: 49,
      imageSrc: '/images/pexels-karolina-grabowska-4219038(1).jpg',
      price: 5,
    },
    {
      _id: 50,
      imageSrc: '/images/pexels-karolina-grabowska-4219038.jpg',
      price: 5,
    },
    {
      _id: 51,
      imageSrc: '/images/pexels-karolina-grabowska-4239017(1).jpg',
      price: 5,
    },
    {
      _id: 52,
      imageSrc: '/images/pexels-karolina-grabowska-4239017.jpg',
      price: 5,
    },
    {
      _id: 53,
      imageSrc: '/images/pexels-karolina-grabowska-4397840(1).jpg',
      price: 5,
    },
    {
      _id: 54,
      imageSrc: '/images/pexels-karolina-grabowska-4397840.jpg',
      price: 5,
    },
    {
      _id: 55,
      imageSrc: '/images/pexels-karolina-grabowska-4464887.jpg',
      price: 5,
    },
    {
      _id: 56,
      imageSrc: '/images/pexels-ketut-subiyanto-4349942.jpg',
      price: 5,
    },
    {
      _id: 57,
      imageSrc: '/images/pexels-ksenia-chernaya-4740522.jpg',
      price: 5,
    },
    {
      _id: 58,
      imageSrc: '/images/pexels-kyle-loftus-3379934.jpg',
      price: 5,
    },
    {
      _id: 59,
      imageSrc: '/images/pexels-laura-james-6097841.jpg',
      price: 5,
    },
    {
      _id: 60,
      imageSrc: '/images/pexels-markus-spiske-92078(1).jpg',
      price: 5,
    },
    {
      _id: 61,
      imageSrc: '/images/pexels-markus-spiske-92078.jpg',
      price: 5,
    },
    {
      _id: 62,
      imageSrc: '/images/pexels-markus-spiske-92080.jpg',
      price: 5,
    },
    {
      _id: 63,
      imageSrc: '/images/pexels-max-vakhtbovych-5997967.jpg',
      price: 5,
    },
    {
      _id: 64,
      imageSrc: '/images/pexels-medhat-ayad-383568.jpg',
      price: 5,
    },
    {
      _id: 65,
      imageSrc: '/images/pexels-mikhail-nilov-6707628.jpg',
      price: 5,
    },
    {
      _id: 66,
      imageSrc: '/images/pexels-mikhail-nilov-6945064(1).jpg',
      price: 5,
    },
    {
      _id: 67,
      imageSrc: '/images/pexels-mikhail-nilov-6945064.jpg',
      price: 5,
    },
    { _id: 68, imageSrc: '/images/pexels-monstera-5874661.jpg', price: 5 },
    { _id: 69, imageSrc: '/images/pexels-monstera-6620861.jpg', price: 5 },
    {
      _id: 70,
      imageSrc: '/images/pexels-monstera-6621434(1).jpg',
      price: 5,
    },
    { _id: 71, imageSrc: '/images/pexels-monstera-6621434.jpg', price: 5 },
    {
      _id: 72,
      imageSrc: '/images/pexels-monstera-6621462(1).jpg',
      price: 5,
    },
    { _id: 73, imageSrc: '/images/pexels-monstera-6621462.jpg', price: 5 },
    {
      _id: 74,
      imageSrc: '/images/pexels-olena-bohovyk-5686478.jpg',
      price: 5,
    },
    {
      _id: 75,
      imageSrc: '/images/pexels-olga-lioncat-7245308.jpg',
      price: 5,
    },
    {
      _id: 76,
      imageSrc: '/images/pexels-olya-kobruseva-5417622.jpg',
      price: 5,
    },
    { _id: 77, imageSrc: '/images/pexels-pixabay-248444.jpg', price: 5 },
    { _id: 78, imageSrc: '/images/pexels-pixabay-531446.jpg', price: 5 },
    {
      _id: 79,
      imageSrc: '/images/pexels-rachel-claire-5490965.jpg',
      price: 5,
    },
    {
      _id: 80,
      imageSrc: '/images/pexels-rachel-claire-5864611.jpg',
      price: 5,
    },
    {
      _id: 81,
      imageSrc: '/images/pexels-sarah-chai-7262407.jpg',
      price: 5,
    },
    {
      _id: 82,
      imageSrc: '/images/pexels-secret-garden-2879818.jpg',
      price: 5,
    },
    {
      _id: 83,
      imageSrc: '/images/pexels-skylar-kang-6045048.jpg',
      price: 5,
    },
    {
      _id: 84,
      imageSrc: '/images/pexels-sunsetoned-5913170.jpg',
      price: 5,
    },
    {
      _id: 85,
      imageSrc: '/images/pexels-tatiana-syrikova-3932929.jpg',
      price: 5,
    },
    {
      _id: 86,
      imageSrc: '/images/pexels-tomas-anunziata-695207(1).jpg',
      price: 5,
    },
    {
      _id: 87,
      imageSrc: '/images/pexels-tomas-anunziata-695207.jpg',
      price: 5,
    },
    { _id: 88, imageSrc: '/images/source.unsplash.jpg', price: 5 },
    { _id: 89, imageSrc: '/images/source.unsplash1.jpg', price: 5 },
    { _id: 90, imageSrc: '/images/source.unsplash10.jpg', price: 5 },
    { _id: 91, imageSrc: '/images/source.unsplash11.jpg', price: 5 },
    { _id: 92, imageSrc: '/images/source.unsplash12.jpg', price: 5 },
    { _id: 93, imageSrc: '/images/source.unsplash13.jpg', price: 5 },
    { _id: 94, imageSrc: '/images/source.unsplash2.jpg', price: 5 },
    { _id: 95, imageSrc: '/images/source.unsplash3.jpg', price: 5 },
    { _id: 96, imageSrc: '/images/source.unsplash4.jpg', price: 5 },
    { _id: 97, imageSrc: '/images/source.unsplash5.jpg', price: 5 },
    { _id: 98, imageSrc: '/images/source.unsplash6.jpg', price: 5 },
    { _id: 99, imageSrc: '/images/source.unsplash7.jpg', price: 5 },
    { _id: 100, imageSrc: '/images/source.unsplash8.jpg', price: 5 },
    { _id: 101, imageSrc: '/images/source.unsplash9.jpg', price: 5 },
  ],
};
